### ISSUE TITLE
Update docs for the 1.5 series

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/rdp#188]
This is meta task to track various things that we need to update in the admin documentation and default FAQ.

- [x] document the ontology management tools
- [ ] add a FAQ section for ontology terms
- [x] mention the theme color variable
- [x] mention in migration that organ systems are now disabled by default

**Comment by sanjarogic** [comment]
**Comments for User Documentation/Profile tab**

Change:
Organ System -> Human Organ System

There are two typos in the paragraph about Organ Systems: 
researches -> researchers
equivalent -> equivalent

Conditionally add:
Additional Profile Categories

For each additional profile category, you can select one or more terms that your research is most relevant to. For simple categories, select terms by checking the appropriate boxes. For ontology categories, use the text box to search for terms of interest and add them to your profile by clicking on them. Selecting no terms within a category is equivalent to selecting all of them.

**Comment by sanjarogic** [comment]
**New text for the Search tab:**

The Search page allows you to search other registered users who chose to share their data publicly and/or with other users of the Registry. If "Include results from partner registries" option is selected, the registry will also connect to remote registries of the RDMM partners and search their "public" users. These results will be displayed in a separate section with the indication from which registry the matches are coming from ("Origin").

There are two ways to search for users: using the "Researcher" or "Gene" tab.

**Searches on the Researcher tab**

The search function on the Researcher tab uses various profile categories to search for registered users. You can search by name, key words in the user's research description or any other category that exists on the Profile page. The search will be preformed using a conjunctive normal form of the specified terms, meaning that all selected categories will need to be satisfied and at least one of the selected terms within each category. The applied search query will be shown at the bottom of the page once the search is performed.

After clicking on the Search button the list of results will be displayed at the bottom of the page.  Clicking on the "View User Profile" button will open a new tab with the user's Profile and gene information.

**Searches on the Gene tab**

The "Gene" tab allows you to search for registered users based on genes they study. Gene symbols are organism-specific and will be matched against the list of known gene symbols for the selected organism (selection made in a dropdown menu). If you want to search for a match using a human gene, but consider orthologs in other model organisms, you would use the secondary dropdown menu to indicate the preferred organism. The ortholog mapping is based on DIOPT results, filtered for DIOPT score >5 and Rank = "high" or "moderate".

You can filter the results of your search using any of the categories displayed on the "Gene" tab page.

**Comment by arteymix** [comment]
From @sanjarogic 

The new text in Documentation/Search should be: "The ortholog mapping is based on [DIOPT](https://www.flyrnai.org/diopt) results, filtered for DIOPT score >5, either best forward or reverse match and Rank = "high" or "moderate".

Also remove the mention to alphabetic search.

**Comment by arteymix** [comment]
Fixed in 178d59860db5a5f942a08941e8cc4c8795155b37

**Comment by sanjarogic** [comment]
Few fixes needed:

1. Networkpartners -> Network partners

2. DIOPT 9.1 results -> DIOPT version 9

3. I would use the following: **filtered for DIOPT score >5, either best forward or reverse match and Rank = "high" or "moderate"** instead of only text
